 CREATE TABLE "TEST"."ADDRESSES"
(
   ID int PRIMARY KEY NOT NULL,
   ADDRESS varchar(25),
   PERSON_ID int NOT NULL
)
;
CREATE TABLE  "TEST"."BAR_TPSCH"
(
   BAR_ID int PRIMARY KEY NOT NULL,
   BAR varchar(10) NOT NULL
)
;
CREATE TABLE  "TEST"."CLAIM"
(
   BRANCH_ID int NOT NULL,
   ITEM_NO varchar(32),
   CLAIM_NO varchar(32) NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   DESCRIPTION varchar(128),
   CONSTRAINT SQL101207155756210 PRIMARY KEY (BRANCH_ID,CLAIM_NO)
)
;
CREATE TABLE   "TEST"."COMPANYUSER"
(
   ID int PRIMARY KEY NOT NULL,
   ROLE_CD int,
   SEX int,
   ADDITIONAL_ROLES varchar(32),
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128)
)
;
CREATE TABLE  "TEST"."CUSTOMER"
(
   CUSTOMER_NO varchar(32) PRIMARY KEY NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   CUSTOMER_NAME varchar(128),
   TAX_ID varchar(16)
)
;
CREATE TABLE  "TEST"."CUSTOMERADDRESS"
(
   ADDRESS_NO int NOT NULL,
   CUSTOMER_NO varchar(32) NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   STREET varchar(128),
   STREET_NO varchar(8),
   CONSTRAINT SQL120328111146450 PRIMARY KEY (ADDRESS_NO,CUSTOMER_NO)
)
;
CREATE TABLE  "TEST"."FOO_TPSCH"
(
   FOO_ID int PRIMARY KEY NOT NULL,
   FOO varchar(10) NOT NULL
)
;
CREATE TABLE  "TEST"."FOOBAR_TPCH"
(
   ID int PRIMARY KEY NOT NULL,
   DISCR varchar(8),
   FOO varchar(8),
   BAR varchar(8)
)
;
CREATE TABLE  "TEST"."FOOBAR_TPSCH"
(
   ID int PRIMARY KEY NOT NULL,
   DISCR varchar(8)
)
;
CREATE TABLE  "TEST"."INSUREDITEM"
(
   BRANCH_ID int NOT NULL,
   ITEM_NO varchar(32) NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   DESCRIPTION varchar(128),
   CONSTRAINT SQL101207155756320 PRIMARY KEY (BRANCH_ID,ITEM_NO)
)
;
CREATE TABLE  "TEST"."INVOICE"
(
   INVOICE_NO varchar(32) PRIMARY KEY NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   INVOICE_DATE date,
   BARCODE varchar(100)
)
;
CREATE TABLE  "TEST"."INVOICECUSTOMER"
(
   INVOICE_NO varchar(32) PRIMARY KEY NOT NULL,
   CUSTOMER_NO varchar(32),
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   ROLE_ID int,
   ADDRESS_NO int
)
;
CREATE TABLE  "TEST"."INVOICEITEM"
(
   ITEM_NO int NOT NULL,
   INVOICE_NO varchar(32) NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   DESCRIPTION varchar(128),
   CONSTRAINT SQL101207134424340 PRIMARY KEY (ITEM_NO,INVOICE_NO)
)
;
CREATE TABLE  "TEST"."INVOICELINE"
(
   LINE_NO int NOT NULL,
   INVOICE_NO varchar(32) NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   TYPE int,
   AMOUNT float(52),
   CUSTOMER_NO varchar(32),
   CONSTRAINT SQL120328111146870 PRIMARY KEY (LINE_NO,INVOICE_NO)
)
;
CREATE TABLE  "TEST"."INVOICERULE"
(
   RULE_CD int NOT NULL,
   INVOICE_NO varchar(32) NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   RULENAME varchar(32),
   CONSTRAINT SQL120328111147170 PRIMARY KEY (RULE_CD,INVOICE_NO)
)
;
CREATE TABLE  "TEST"."INVOICESUBLINE"
(
   SUB_LINE_NO int NOT NULL,
   LINE_NO int NOT NULL,
   INVOICE_NO varchar(32) NOT NULL,
   RULE_CD int,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   NAME varchar(32),
   CONSTRAINT SQL120328111147060 PRIMARY KEY (SUB_LINE_NO,LINE_NO,INVOICE_NO)
)
;
CREATE TABLE  "TEST"."INVOICESUBRULE"
(
   SUBRULE_CD int NOT NULL,
   RULE_CD int NOT NULL,
   INVOICE_NO varchar(32) NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   SUBRULENAME varchar(32),
   CONSTRAINT SQL120328111147300 PRIMARY KEY (SUBRULE_CD,RULE_CD,INVOICE_NO)
)
;
CREATE TABLE  "TEST"."PERSONS"
(
   ID int PRIMARY KEY NOT NULL,
   NAME varchar(25)
)
;
CREATE TABLE  "TEST"."PHONES"
(
   USR_ID int NOT NULL,
   PHONE varchar(25)
)
;
CREATE TABLE  "TEST"."ROLES"
(
   ID int PRIMARY KEY NOT NULL,
   ROLE_DSC varchar(90) DEFAULT '' NOT NULL
)
;
CREATE TABLE  "TEST"."USERPROFILE"
(
   ID int NOT NULL,
   PROFILE_ID int NOT NULL,
   PROF_NM char(30) DEFAULT '' NOT NULL
)
;
CREATE TABLE  "TEST"."USERS"
(
   ID int PRIMARY KEY NOT NULL,
   USR_ID char(8) DEFAULT '' NOT NULL,
   USR_NM char(30) DEFAULT '' NOT NULL,
   ROLE_ID int DEFAULT 0
)
;
CREATE UNIQUE INDEX SQL100928145821780 ON "TEST"."ADDRESSES"(ID)
;
ALTER TABLE "TEST"."BAR_TPSCH"
ADD CONSTRAINT FK_BAR_ID_2_ID
FOREIGN KEY (BAR_ID)
REFERENCES "TEST"."FOOBAR_TPSCH"(ID)
;
CREATE INDEX SQL120328111148140 ON "TEST"."BAR_TPSCH"(BAR_ID)
;
CREATE UNIQUE INDEX SQL120328111147750 ON "TEST"."BAR_TPSCH"(BAR_ID)
;
CREATE UNIQUE INDEX SQL101207155756210 ON "TEST"."CLAIM"
(
  BRANCH_ID,
  CLAIM_NO
)
;
CREATE UNIQUE INDEX SQL120328111147420 ON "TEST"."COMPANYUSER"(ID)
;
CREATE UNIQUE INDEX SQL120328111146280 ON "TEST"."CUSTOMER"(CUSTOMER_NO)
;
ALTER TABLE "TEST"."CUSTOMERADDRESS"
ADD CONSTRAINT FK_CUST_ADDR_2_CUST 
FOREIGN KEY (CUSTOMER_NO)
REFERENCES "TEST"."CUSTOMER"(CUSTOMER_NO)
;
CREATE UNIQUE INDEX SQL120328111146450 ON "TEST"."CUSTOMERADDRESS"
(
  ADDRESS_NO,
  CUSTOMER_NO
)
;
CREATE INDEX SQL120328111148161 ON "TEST"."CUSTOMERADDRESS"(CUSTOMER_NO)
;
ALTER TABLE "TEST"."FOO_TPSCH"
ADD CONSTRAINT FK_FOO_ID_2_ID
FOREIGN KEY (FOO_ID)
REFERENCES "TEST"."FOOBAR_TPSCH"(ID)
;
CREATE UNIQUE INDEX SQL120328111147970 ON "TEST"."FOO_TPSCH"(FOO_ID)
;
CREATE INDEX SQL120328111148160 ON "TEST"."FOO_TPSCH"(FOO_ID)
;
CREATE UNIQUE INDEX SQL120328111147530 ON "TEST"."FOOBAR_TPCH"(ID)
;
CREATE UNIQUE INDEX SQL120328111147640 ON "TEST"."FOOBAR_TPSCH"(ID)
;
CREATE UNIQUE INDEX SQL101207155756320 ON "TEST"."INSUREDITEM"
(
  BRANCH_ID,
  ITEM_NO
)
;
CREATE UNIQUE INDEX SQL120328111146580 ON "TEST"."INVOICE"(INVOICE_NO)
;
ALTER TABLE "TEST"."INVOICECUSTOMER"
ADD CONSTRAINT FK_INV_CUST_2_CUST
FOREIGN KEY (CUSTOMER_NO)
REFERENCES "TEST"."CUSTOMER"(CUSTOMER_NO)
;
ALTER TABLE "TEST"."INVOICECUSTOMER"
ADD CONSTRAINT FK_INV_CUST_2_INV
FOREIGN KEY (INVOICE_NO)
REFERENCES "TEST"."INVOICE"(INVOICE_NO)
;
CREATE INDEX SQL120328111148750 ON "TEST"."INVOICECUSTOMER"(CUSTOMER_NO)
;
CREATE INDEX SQL120328111148940 ON "TEST"."INVOICECUSTOMER"(INVOICE_NO)
;
CREATE UNIQUE INDEX SQL120328111146670 ON "TEST"."INVOICECUSTOMER"(INVOICE_NO)
;
CREATE UNIQUE INDEX SQL101207134424340 ON "TEST"."INVOICEITEM"
(
  ITEM_NO,
  INVOICE_NO
)
;
ALTER TABLE "TEST"."INVOICELINE"
ADD CONSTRAINT FK_INV_LINE_2_CUST
FOREIGN KEY (CUSTOMER_NO)
REFERENCES "TEST"."CUSTOMER"(CUSTOMER_NO)
;
ALTER TABLE "TEST"."INVOICELINE"
ADD CONSTRAINT FK_INV_LINE_2_INV
FOREIGN KEY (INVOICE_NO)
REFERENCES "TEST"."INVOICE"(INVOICE_NO)
;
CREATE UNIQUE INDEX SQL120328111146870 ON "TEST"."INVOICELINE"
(
  LINE_NO,
  INVOICE_NO
)
;
CREATE INDEX SQL120328111148330 ON "TEST"."INVOICELINE"(CUSTOMER_NO)
;
CREATE INDEX SQL120328111148230 ON "TEST"."INVOICELINE"(INVOICE_NO)
;
ALTER TABLE "TEST"."INVOICERULE"
ADD CONSTRAINT FK_INV_RULE_2_INV
FOREIGN KEY (INVOICE_NO)
REFERENCES "TEST"."INVOICE"(INVOICE_NO)
;
CREATE UNIQUE INDEX SQL120328111147170 ON "TEST"."INVOICERULE"
(
  RULE_CD,
  INVOICE_NO
)
;
CREATE INDEX SQL120328111148410 ON "TEST"."INVOICERULE"(INVOICE_NO)
;
ALTER TABLE "TEST"."INVOICESUBLINE"
ADD CONSTRAINT FK_INV_SLINE_2_LINE
FOREIGN KEY
(
  LINE_NO,
  INVOICE_NO
)
REFERENCES "TEST"."INVOICELINE"
(
  LINE_NO,
  INVOICE_NO
)
;
ALTER TABLE "TEST"."INVOICESUBLINE"
ADD CONSTRAINT FK_INV_SLINE_2_RULE
FOREIGN KEY
(
  RULE_CD,
  INVOICE_NO
)
REFERENCES "TEST"."INVOICERULE"
(
  RULE_CD,
  INVOICE_NO
)
;
CREATE INDEX SQL120328111148500 ON "TEST"."INVOICESUBLINE"
(
  LINE_NO,
  INVOICE_NO
)
;
CREATE INDEX SQL120328111148560 ON "TEST"."INVOICESUBLINE"
(
  RULE_CD,
  INVOICE_NO
)
;
CREATE UNIQUE INDEX SQL120328111147060 ON "TEST"."INVOICESUBLINE"
(
  SUB_LINE_NO,
  LINE_NO,
  INVOICE_NO
)
;
ALTER TABLE "TEST"."INVOICESUBRULE"
ADD CONSTRAINT FK_INV_SRULE_2_RULE
FOREIGN KEY
(
  RULE_CD,
  INVOICE_NO
)
REFERENCES "TEST"."INVOICERULE"
(
  RULE_CD,
  INVOICE_NO
)
;
CREATE INDEX SQL120328111148660 ON "TEST"."INVOICESUBRULE"
(
  RULE_CD,
  INVOICE_NO
)
;
CREATE UNIQUE INDEX SQL120328111147300 ON "TEST"."INVOICESUBRULE"
(
  SUBRULE_CD,
  RULE_CD,
  INVOICE_NO
)
;
CREATE UNIQUE INDEX SQL100928141131380 ON "TEST"."PERSONS"(ID)
;
CREATE UNIQUE INDEX SQL100712031304040 ON "TEST"."ROLES"(ID)
;
ALTER TABLE "TEST"."USERPROFILE"
ADD CONSTRAINT FK_PROFILE_2_USER
FOREIGN KEY (ID)
REFERENCES "TEST"."USERS"(ID)
;
CREATE INDEX SQL130520150055810 ON "TEST"."USERPROFILE"(ID)
;
ALTER TABLE "TEST"."USERS"
ADD CONSTRAINT FK_USERROLE
FOREIGN KEY (ROLE_ID) 
REFERENCES "TEST"."ROLES"(ID)
;
CREATE UNIQUE INDEX SQL100712031118840 ON "TEST"."USERS"(ID)
;
CREATE INDEX IDX_USERS ON "TEST"."USERS"(ROLE_ID)
;
CREATE INDEX SQL100712031459060 ON "TEST"."USERS"(ROLE_ID)
;

CREATE TABLE "OTHERTEST"."ADDRESSES"
(
   ID int PRIMARY KEY NOT NULL,
   ADDRESS varchar(25),
   PERSON_ID int NOT NULL
)
;
CREATE TABLE "OTHERTEST"."BAR_TPSCH"
(
   BAR_ID int PRIMARY KEY NOT NULL,
   BAR varchar(10) NOT NULL
)
;
CREATE TABLE "OTHERTEST"."CLAIM"
(
   BRANCH_ID int NOT NULL,
   ITEM_NO varchar(32),
   CLAIM_NO varchar(32) NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   DESCRIPTION varchar(128),
   CONSTRAINT SQL101207155756210 PRIMARY KEY (BRANCH_ID,CLAIM_NO)
)
;
CREATE TABLE "OTHERTEST"."COMPANYUSER"
(
   ID int PRIMARY KEY NOT NULL,
   ROLE_CD int,
   SEX int,
   ADDITIONAL_ROLES varchar(32),
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128)
)
;
CREATE TABLE "OTHERTEST"."CUSTOMER"
(
   CUSTOMER_NO varchar(32) PRIMARY KEY NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   CUSTOMER_NAME varchar(128),
   TAX_ID varchar(16)
)
;
CREATE TABLE "OTHERTEST"."CUSTOMERADDRESS"
(
   ADDRESS_NO int NOT NULL,
   CUSTOMER_NO varchar(32) NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   STREET varchar(128),
   STREET_NO varchar(8),
   CONSTRAINT SQL120328111146450 PRIMARY KEY (ADDRESS_NO,CUSTOMER_NO)
)
;
CREATE TABLE "OTHERTEST"."FOO_TPSCH"
(
   FOO_ID int PRIMARY KEY NOT NULL,
   FOO varchar(10) NOT NULL
)
;
CREATE TABLE "OTHERTEST"."FOOBAR_TPCH"
(
   ID int PRIMARY KEY NOT NULL,
   DISCR varchar(8),
   FOO varchar(8),
   BAR varchar(8)
)
;
CREATE TABLE "OTHERTEST"."FOOBAR_TPSCH"
(
   ID int PRIMARY KEY NOT NULL,
   DISCR varchar(8)
)
;
CREATE TABLE "OTHERTEST"."INSUREDITEM"
(
   BRANCH_ID int NOT NULL,
   ITEM_NO varchar(32) NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   DESCRIPTION varchar(128),
   CONSTRAINT SQL101207155756320 PRIMARY KEY (BRANCH_ID,ITEM_NO)
)
;
CREATE TABLE "OTHERTEST"."INVOICE"
(
   INVOICE_NO varchar(32) PRIMARY KEY NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   INVOICE_DATE date,
   BARCODE varchar(100)
)
;
CREATE TABLE "OTHERTEST"."INVOICECUSTOMER"
(
   INVOICE_NO varchar(32) PRIMARY KEY NOT NULL,
   CUSTOMER_NO varchar(32),
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   ROLE_ID int,
   ADDRESS_NO int
)
;
CREATE TABLE "OTHERTEST"."INVOICEITEM"
(
   ITEM_NO int NOT NULL,
   INVOICE_NO varchar(32) NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   DESCRIPTION varchar(128),
   CONSTRAINT SQL101207134424340 PRIMARY KEY (ITEM_NO,INVOICE_NO)
)
;
CREATE TABLE "OTHERTEST"."INVOICELINE"
(
   LINE_NO int NOT NULL,
   INVOICE_NO varchar(32) NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   TYPE int,
   AMOUNT float(52),
   CUSTOMER_NO varchar(32),
   CONSTRAINT SQL120328111146870 PRIMARY KEY (LINE_NO,INVOICE_NO)
)
;
CREATE TABLE "OTHERTEST"."INVOICERULE"
(
   RULE_CD int NOT NULL,
   INVOICE_NO varchar(32) NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   RULENAME varchar(32),
   CONSTRAINT SQL120328111147170 PRIMARY KEY (RULE_CD,INVOICE_NO)
)
;
CREATE TABLE "OTHERTEST"."INVOICESUBLINE"
(
   SUB_LINE_NO int NOT NULL,
   LINE_NO int NOT NULL,
   INVOICE_NO varchar(32) NOT NULL,
   RULE_CD int,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   NAME varchar(32),
   CONSTRAINT SQL120328111147060 PRIMARY KEY (SUB_LINE_NO,LINE_NO,INVOICE_NO)
)
;
CREATE TABLE "OTHERTEST"."INVOICESUBRULE"
(
   SUBRULE_CD int NOT NULL,
   RULE_CD int NOT NULL,
   INVOICE_NO varchar(32) NOT NULL,
   LAST_MODIFIED timestamp NOT NULL,
   LAST_MODIFIED_BY varchar(128),
   SUBRULENAME varchar(32),
   CONSTRAINT SQL120328111147300 PRIMARY KEY (SUBRULE_CD,RULE_CD,INVOICE_NO)
)
;
CREATE TABLE "OTHERTEST"."PERSONS"
(
   ID int PRIMARY KEY NOT NULL,
   NAME varchar(25)
)
;
CREATE TABLE "OTHERTEST"."PHONES"
(
   USR_ID int NOT NULL,
   PHONE varchar(25)
)
;
CREATE TABLE "OTHERTEST"."ROLES"
(
   ID int PRIMARY KEY NOT NULL,
   ROLE_DSC varchar(90) DEFAULT '' NOT NULL
)
;
CREATE TABLE "OTHERTEST"."USERPROFILE"
(
   ID int NOT NULL,
   PROFILE_ID int NOT NULL,
   PROF_NM char(30) DEFAULT '' NOT NULL
)
;
CREATE TABLE "OTHERTEST"."USERS"
(
   ID int PRIMARY KEY NOT NULL,
   USR_ID char(8) DEFAULT '' NOT NULL,
   USR_NM char(30) DEFAULT '' NOT NULL,
   ROLE_ID int DEFAULT 0
)
;
CREATE UNIQUE INDEX SQL100928145821780 ON "OTHERTEST"."ADDRESSES"(ID)
;
ALTER TABLE "OTHERTEST"."BAR_TPSCH"
ADD CONSTRAINT FK_BAR_ID_2_ID
FOREIGN KEY (BAR_ID)
REFERENCES "OTHERTEST"."FOOBAR_TPSCH"(ID)
;
CREATE INDEX SQL120328111148140 ON "OTHERTEST"."BAR_TPSCH"(BAR_ID)
;
CREATE UNIQUE INDEX SQL120328111147750 ON "OTHERTEST"."BAR_TPSCH"(BAR_ID)
;
CREATE UNIQUE INDEX SQL101207155756210 ON "OTHERTEST"."CLAIM"
(
  BRANCH_ID,
  CLAIM_NO
)
;
CREATE UNIQUE INDEX SQL120328111147420 ON "OTHERTEST"."COMPANYUSER"(ID)
;
CREATE UNIQUE INDEX SQL120328111146280 ON "OTHERTEST"."CUSTOMER"(CUSTOMER_NO)
;
ALTER TABLE "OTHERTEST"."CUSTOMERADDRESS"
ADD CONSTRAINT FK_CUST_ADDR_2_CUST
FOREIGN KEY (CUSTOMER_NO)
REFERENCES "OTHERTEST"."CUSTOMER"(CUSTOMER_NO)
;
CREATE UNIQUE INDEX SQL120328111146450 ON "OTHERTEST"."CUSTOMERADDRESS"
(
  ADDRESS_NO,
  CUSTOMER_NO
)
;
CREATE INDEX SQL120328111148161 ON "OTHERTEST"."CUSTOMERADDRESS"(CUSTOMER_NO)
;
ALTER TABLE "OTHERTEST"."FOO_TPSCH"
ADD CONSTRAINT FK_FOO_ID_2_ID
FOREIGN KEY (FOO_ID)
REFERENCES "OTHERTEST"."FOOBAR_TPSCH"(ID)
;
CREATE UNIQUE INDEX SQL120328111147970 ON "OTHERTEST"."FOO_TPSCH"(FOO_ID)
;
CREATE INDEX SQL120328111148160 ON "OTHERTEST"."FOO_TPSCH"(FOO_ID)
;
CREATE UNIQUE INDEX SQL120328111147530 ON "OTHERTEST"."FOOBAR_TPCH"(ID)
;
CREATE UNIQUE INDEX SQL120328111147640 ON "OTHERTEST"."FOOBAR_TPSCH"(ID)
;
CREATE UNIQUE INDEX SQL101207155756320 ON "OTHERTEST"."INSUREDITEM"
(
  BRANCH_ID,
  ITEM_NO
)
;
CREATE UNIQUE INDEX SQL120328111146580 ON "OTHERTEST"."INVOICE"(INVOICE_NO)
;
ALTER TABLE "OTHERTEST"."INVOICECUSTOMER"
ADD CONSTRAINT FK_INV_CUST_2_CUST
FOREIGN KEY (CUSTOMER_NO)
REFERENCES "OTHERTEST"."CUSTOMER"(CUSTOMER_NO)
;
ALTER TABLE "OTHERTEST"."INVOICECUSTOMER"
ADD CONSTRAINT FK_INV_CUST_2_INV
FOREIGN KEY (INVOICE_NO)
REFERENCES "OTHERTEST"."INVOICE"(INVOICE_NO)
;
CREATE INDEX SQL120328111148750 ON "OTHERTEST"."INVOICECUSTOMER"(CUSTOMER_NO)
;
CREATE INDEX SQL120328111148940 ON "OTHERTEST"."INVOICECUSTOMER"(INVOICE_NO)
;
CREATE UNIQUE INDEX SQL120328111146670 ON "OTHERTEST"."INVOICECUSTOMER"(INVOICE_NO)
;
CREATE UNIQUE INDEX SQL101207134424340 ON "OTHERTEST"."INVOICEITEM"
(
  ITEM_NO,
  INVOICE_NO
)
;
ALTER TABLE "OTHERTEST"."INVOICELINE"
ADD CONSTRAINT FK_INV_LINE_2_CUST
FOREIGN KEY (CUSTOMER_NO)
REFERENCES "OTHERTEST"."CUSTOMER"(CUSTOMER_NO)
;
ALTER TABLE "OTHERTEST"."INVOICELINE"
ADD CONSTRAINT FK_INV_LINE_2_INV
FOREIGN KEY (INVOICE_NO)
REFERENCES "OTHERTEST"."INVOICE"(INVOICE_NO)
;
CREATE UNIQUE INDEX SQL120328111146870 ON "OTHERTEST"."INVOICELINE"
(
  LINE_NO,
  INVOICE_NO
)
;
CREATE INDEX SQL120328111148330 ON "OTHERTEST"."INVOICELINE"(CUSTOMER_NO)
;
CREATE INDEX SQL120328111148230 ON "OTHERTEST"."INVOICELINE"(INVOICE_NO)
;
ALTER TABLE "OTHERTEST"."INVOICERULE"
ADD CONSTRAINT FK_INV_RULE_2_INV
FOREIGN KEY (INVOICE_NO)
REFERENCES "OTHERTEST"."INVOICE"(INVOICE_NO)
;
CREATE UNIQUE INDEX SQL120328111147170 ON "OTHERTEST"."INVOICERULE"
(
  RULE_CD,
  INVOICE_NO
)
;
CREATE INDEX SQL120328111148410 ON "OTHERTEST"."INVOICERULE"(INVOICE_NO)
;
ALTER TABLE "OTHERTEST"."INVOICESUBLINE"
ADD CONSTRAINT FK_INV_SLINE_2_LINE
FOREIGN KEY
(
  LINE_NO,
  INVOICE_NO
)
REFERENCES "OTHERTEST"."INVOICELINE"
(
  LINE_NO,
  INVOICE_NO
)
;
ALTER TABLE "OTHERTEST"."INVOICESUBLINE"
ADD CONSTRAINT FK_INV_SLINE_2_RULE
FOREIGN KEY
(
  RULE_CD,
  INVOICE_NO
)
REFERENCES "OTHERTEST"."INVOICERULE"
(
  RULE_CD,
  INVOICE_NO
)
;
CREATE INDEX SQL120328111148500 ON "OTHERTEST"."INVOICESUBLINE"
(
  LINE_NO,
  INVOICE_NO
)
;
CREATE INDEX SQL120328111148560 ON "OTHERTEST"."INVOICESUBLINE"
(
  RULE_CD,
  INVOICE_NO
)
;
CREATE UNIQUE INDEX SQL120328111147060 ON "OTHERTEST"."INVOICESUBLINE"
(
  SUB_LINE_NO,
  LINE_NO,
  INVOICE_NO
)
;
ALTER TABLE "OTHERTEST"."INVOICESUBRULE"
ADD CONSTRAINT FK_INV_SRULE_2_RULE
FOREIGN KEY
(
  RULE_CD,
  INVOICE_NO
)
REFERENCES "OTHERTEST"."INVOICERULE"
(
  RULE_CD,
  INVOICE_NO
)
;
CREATE INDEX SQL120328111148660 ON "OTHERTEST"."INVOICESUBRULE"
(
  RULE_CD,
  INVOICE_NO
)
;
CREATE UNIQUE INDEX SQL120328111147300 ON "OTHERTEST"."INVOICESUBRULE"
(
  SUBRULE_CD,
  RULE_CD,
  INVOICE_NO
)
;
CREATE UNIQUE INDEX SQL100928141131380 ON "OTHERTEST"."PERSONS"(ID)
;
CREATE UNIQUE INDEX SQL100712031304040 ON "OTHERTEST"."ROLES"(ID)
;
ALTER TABLE "OTHERTEST"."USERPROFILE"
ADD CONSTRAINT FK_PROFILE_2_USER
FOREIGN KEY (ID)
REFERENCES "OTHERTEST"."USERS"(ID)
;
CREATE INDEX SQL130520155733530 ON "OTHERTEST"."USERPROFILE"(ID)
;
ALTER TABLE "OTHERTEST"."USERS"
ADD CONSTRAINT FK_USERROLE
FOREIGN KEY (ROLE_ID)
REFERENCES "OTHERTEST"."ROLES"(ID)
;
CREATE UNIQUE INDEX SQL100712031118840 ON "OTHERTEST"."USERS"(ID)
;
CREATE INDEX IDX_USERS ON "OTHERTEST"."USERS"(ROLE_ID)
;
CREATE INDEX SQL100712031459060 ON "OTHERTEST"."USERS"(ROLE_ID)
;


INSERT INTO "TEST"."ROLES" (ID,ROLE_DSC) VALUES (0,'unspecified role');
INSERT INTO "TEST"."ROLES" (ID,ROLE_DSC) VALUES (1,'info user');
INSERT INTO "TEST"."ROLES" (ID,ROLE_DSC) VALUES (2,'data entry user');
INSERT INTO "TEST"."ROLES" (ID,ROLE_DSC) VALUES (3,'underwriter');
INSERT INTO "TEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (1,'Old     ','name                          ',0);
INSERT INTO "TEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (100,'US00    ','name                          ',0);
INSERT INTO "TEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (101,'US00    ','name                          ',0);
INSERT INTO "TEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (112,'USRID_00','name                          ',0);
INSERT INTO "TEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (1012,'US00    ','name                          ',0);
INSERT INTO "TEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (1013,'US00    ','name                          ',0);
INSERT INTO "TEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (1815,'US00    ','This is my name               ',1);
INSERT INTO "TEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (2815,'US00    ','This is my name               ',1);
INSERT INTO "TEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (3815,'US00    ','This is my name               ',1);
INSERT INTO "TEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (4815,'US00    ','This is my name               ',1);
INSERT INTO "TEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (4816,'US00    ','This is my name               ',1);
INSERT INTO "TEST"."CLAIM" (BRANCH_ID,ITEM_NO,CLAIM_NO,LAST_MODIFIED,LAST_MODIFIED_BY,DESCRIPTION) VALUES (1,'house01','AA1',{ts '2010-12-07 16:43:24.777000'},null,null);
INSERT INTO "TEST"."COMPANYUSER" (ID,ROLE_CD,SEX,ADDITIONAL_ROLES,LAST_MODIFIED,LAST_MODIFIED_BY) VALUES (10,0,1,'',{ts '2016-04-19 13:07:51.866000'},'who');
INSERT INTO "TEST"."INSUREDITEM" (BRANCH_ID,ITEM_NO,LAST_MODIFIED,LAST_MODIFIED_BY,DESCRIPTION) VALUES (1,'house01',{ts '2010-12-07 16:43:24.824000'},null,null);

INSERT INTO "OTHERTEST"."CLAIM" (BRANCH_ID,ITEM_NO,CLAIM_NO,LAST_MODIFIED,LAST_MODIFIED_BY,DESCRIPTION) VALUES (1,'house01','AA1',{ts '2010-12-07 16:43:24.777000'},null,null);
INSERT INTO "OTHERTEST"."INSUREDITEM" (BRANCH_ID,ITEM_NO,LAST_MODIFIED,LAST_MODIFIED_BY,DESCRIPTION) VALUES (1,'house01',{ts '2010-12-07 16:43:24.824000'},null,null);
INSERT INTO "OTHERTEST"."ROLES" (ID,ROLE_DSC) VALUES (0,'unspecified role');
INSERT INTO "OTHERTEST"."ROLES" (ID,ROLE_DSC) VALUES (1,'info user');
INSERT INTO "OTHERTEST"."ROLES" (ID,ROLE_DSC) VALUES (2,'data entry user');
INSERT INTO "OTHERTEST"."ROLES" (ID,ROLE_DSC) VALUES (3,'underwriter');
INSERT INTO "OTHERTEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (1,'Old     ','Old Name                      ',0);
INSERT INTO "OTHERTEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (100,'US00    ','name                          ',0);
INSERT INTO "OTHERTEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (101,'US00    ','name                          ',0);
INSERT INTO "OTHERTEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (1012,'US00    ','name                          ',0);
INSERT INTO "OTHERTEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (1013,'US00    ','name                          ',0);
INSERT INTO "OTHERTEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (1815,'US00    ','This is my name               ',1);
INSERT INTO "OTHERTEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (2815,'US00    ','This is my name               ',1);
INSERT INTO "OTHERTEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (3815,'US00    ','This is my name               ',1);
INSERT INTO "OTHERTEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (4815,'US00    ','This is my name               ',1);
INSERT INTO "OTHERTEST"."USERS" (ID,USR_ID,USR_NM,ROLE_ID) VALUES (4816,'US00    ','This is my name               ',1);